In [68]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold
from sklearn import preprocessing

In [69]:
data = pd.read_csv('data/dataset_logical_filter.csv')
df = pd.DataFrame(data)
df

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
292,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
293,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
294,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
295,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
296,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [70]:
print(df['Fuel_Type'].value_counts())

Fuel_Type
Petrol    239
Diesel     58
Name: count, dtype: int64

In [71]:
df

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
292,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
293,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
294,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
295,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
296,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [72]:
df['Fuel_Type'] = df['Fuel_Type'].map({'Petrol': 0, 'Diesel': 1})
df['Seller_Type'] = df['Seller_Type'].map({'Dealer': 0, 'Individual': 1})
df['Transmission'] = df['Transmission'].map({'Manual': 0, 'Automatic': 1})

In [73]:
df['Car_Age'] = 2019 - df['Year']
df['Age_Squared'] = df['Car_Age'] ** 2
df['Kms_Squared'] = df['Kms_Driven'] ** 2

In [74]:
print(df.isnull().sum())

Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
Car_Age          0
Age_Squared      0
Kms_Squared      0
dtype: int64

In [75]:
X_raw = df.drop(['Selling_Price', 'Year'], axis=1, errors='ignore')
y = df['Selling_Price']

In [76]:
scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
X_scaled_array = scaler.fit_transform(X_raw)
X = pd.DataFrame(X_scaled_array, columns=X_raw.columns)

In [77]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)
model = LinearRegression()
scores = []
fold_number = 1
for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    score = r2_score(y_test, y_pred)
    scores.append(score)
    print(f"{fold_number} | {score:.4f}")
    fold_number += 1
print(np.mean(scores))

1 | 0.8963
2 | 0.8717
3 | 0.8673
4 | 0.8944
5 | 0.8645
0.8788241439290017